### PR TITLE
Fairly minor changes to support geoserver-independent geonode layer import handler.

### PR DESCRIPTION
**Pull request by JivanAmara**

### CODE REVIEW

**Comment by jj0hns0n** [comment]
can we disable flake8 for now?

**Comment by ghost** [comment]
I can do flake8 fixups, let's see

**Comment by JivanAmara** [comment]
Hi Sasha, are you tackling the flake8 issues, or should I pick them up?

**Comment by JivanAmara** [comment]
N/M, just saw & merged your fixes.

**Comment by ghost** [comment]
Looks fine (don't sweat the coverage stuff, it's just there to remind us)

**Pull request merged**
